# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1004, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(155, 312))
        self.centralwidget.setObjectName("centralwidget")
        self.dockWidget_9 = QtWidgets.QDockWidget(self.centralwidget)
        self.dockWidget_9.setGeometry(QtCore.QRect(0, 0, 500, 354))
        self.dockWidget_9.setMinimumSize(QtCore.QSize(500, 111))
        self.dockWidget_9.setObjectName("dockWidget_9")
        self.dockWidgetContents_9 = QtWidgets.QWidget()
        self.dockWidgetContents_9.setObjectName("dockWidgetContents_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dockWidgetContents_9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dockWidget_9.setWidget(self.dockWidgetContents_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1004, 21))
        self.menubar.setToolTipDuration(1)
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuCriar_Dataset = QtWidgets.QMenu(self.menuArquivo)
        self.menuCriar_Dataset.setObjectName("menuCriar_Dataset")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFerramentas = QtWidgets.QMenu(self.menubar)
        self.menuFerramentas.setObjectName("menuFerramentas")
        self.menuProje_o = QtWidgets.QMenu(self.menuFerramentas)
        self.menuProje_o.setObjectName("menuProje_o")
        self.menuPr_Processamento = QtWidgets.QMenu(self.menuFerramentas)
        self.menuPr_Processamento.setObjectName("menuPr_Processamento")
        self.menuFiltros = QtWidgets.QMenu(self.menuPr_Processamento)
        self.menuFiltros.setObjectName("menuFiltros")
        self.menuPrefer_ncias = QtWidgets.QMenu(self.menubar)
        self.menuPrefer_ncias.setObjectName("menuPrefer_ncias")
        self.menuExibir = QtWidgets.QMenu(self.menubar)
        self.menuExibir.setObjectName("menuExibir")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_6 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_6.setMinimumSize(QtCore.QSize(500, 243))
        self.dockWidget_6.setObjectName("dockWidget_6")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.dockWidget_6.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_6)
        self.dockWidget_7 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_7.setMinimumSize(QtCore.QSize(500, 111))
        self.dockWidget_7.setObjectName("dockWidget_7")
        self.dockWidgetContents_7 = QtWidgets.QWidget()
        self.dockWidgetContents_7.setObjectName("dockWidgetContents_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents_7)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.dockWidgetContents_7)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(38)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(37, item)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.dockWidget_7.setWidget(self.dockWidgetContents_7)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_7)
        self.dockWidget_8 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_8.setMinimumSize(QtCore.QSize(500, 243))
        self.dockWidget_8.setToolTipDuration(1)
        self.dockWidget_8.setObjectName("dockWidget_8")
        self.dockWidgetContents_8 = QtWidgets.QWidget()
        self.dockWidgetContents_8.setObjectName("dockWidgetContents_8")
        self.dockWidget_8.setWidget(self.dockWidgetContents_8)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_8)
        self.actionAbrir_Dataset = QtWidgets.QAction(MainWindow)
        self.actionAbrir_Dataset.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionAbrir_Dataset.setObjectName("actionAbrir_Dataset")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionAtalhos = QtWidgets.QAction(MainWindow)
        self.actionAtalhos.setObjectName("actionAtalhos")
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.actionDeteccao_de_Caracteristicas = QtWidgets.QAction(MainWindow)
        self.actionDeteccao_de_Caracteristicas.setObjectName("actionDeteccao_de_Caracteristicas")
        self.actionPCA = QtWidgets.QAction(MainWindow)
        self.actionPCA.setObjectName("actionPCA")
        self.actionTSNE = QtWidgets.QAction(MainWindow)
        self.actionTSNE.setObjectName("actionTSNE")
        self.actionSAMMON = QtWidgets.QAction(MainWindow)
        self.actionSAMMON.setObjectName("actionSAMMON")
        self.actionMDS = QtWidgets.QAction(MainWindow)
        self.actionMDS.setObjectName("actionMDS")
        self.actionNormalizar_Valores = QtWidgets.QAction(MainWindow)
        self.actionNormalizar_Valores.setCheckable(True)
        self.actionNormalizar_Valores.setChecked(True)
        self.actionNormalizar_Valores.setObjectName("actionNormalizar_Valores")
        self.actionRecorteLivre = QtWidgets.QAction(MainWindow)
        self.actionRecorteLivre.setObjectName("actionRecorteLivre")
        self.actionDividir_Imagem = QtWidgets.QAction(MainWindow)
        self.actionDividir_Imagem.setObjectName("actionDividir_Imagem")
        self.actionEqualizacao = QtWidgets.QAction(MainWindow)
        self.actionEqualizacao.setObjectName("actionEqualizacao")
        self.actionMediana = QtWidgets.QAction(MainWindow)
        self.actionMediana.setObjectName("actionMediana")
        self.actionBinarizacao = QtWidgets.QAction(MainWindow)
        self.actionBinarizacao.setObjectName("actionBinarizacao")
        self.actionInversao = QtWidgets.QAction(MainWindow)
        self.actionInversao.setObjectName("actionInversao")
        self.actionCriar_Classe = QtWidgets.QAction(MainWindow)
        self.actionCriar_Classe.setObjectName("actionCriar_Classe")
        self.actionOperadores = QtWidgets.QAction(MainWindow)
        self.actionOperadores.setObjectName("actionOperadores")
        self.actionteste = QtWidgets.QAction(MainWindow)
        self.actionteste.setObjectName("actionteste")
        self.actionPre_Processamento_Automatico = QtWidgets.QAction(MainWindow)
        self.actionPre_Processamento_Automatico.setObjectName("actionPre_Processamento_Automatico")
        self.actionImagens = QtWidgets.QAction(MainWindow)
        self.actionImagens.setObjectName("actionImagens")
        self.menuCriar_Dataset.addAction(self.actionCriar_Classe)
        self.menuCriar_Dataset.addAction(self.actionDividir_Imagem)
        self.menuArquivo.addAction(self.actionAbrir_Dataset)
        self.menuArquivo.addAction(self.menuCriar_Dataset.menuAction())
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSair)
        self.menuHelp.addAction(self.actionAtalhos)
        self.menuHelp.addAction(self.actionSobre)
        self.menuProje_o.addAction(self.actionPCA)
        self.menuProje_o.addAction(self.actionTSNE)
        self.menuProje_o.addAction(self.actionSAMMON)
        self.menuProje_o.addAction(self.actionMDS)
        self.menuFiltros.addAction(self.actionEqualizacao)
        self.menuFiltros.addAction(self.actionMediana)
        self.menuFiltros.addAction(self.actionBinarizacao)
        self.menuFiltros.addAction(self.actionInversao)
        self.menuFiltros.addAction(self.actionOperadores)
        self.menuPr_Processamento.addAction(self.actionRecorteLivre)
        self.menuPr_Processamento.addSeparator()
        self.menuPr_Processamento.addAction(self.menuFiltros.menuAction())
        self.menuFerramentas.addAction(self.menuPr_Processamento.menuAction())
        self.menuFerramentas.addAction(self.actionPre_Processamento_Automatico)
        self.menuFerramentas.addSeparator()
        self.menuFerramentas.addAction(self.actionDeteccao_de_Caracteristicas)
        self.menuFerramentas.addAction(self.menuProje_o.menuAction())
        self.menuPrefer_ncias.addAction(self.actionNormalizar_Valores)
        self.menuExibir.addAction(self.actionImagens)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuExibir.menuAction())
        self.menubar.addAction(self.menuFerramentas.menuAction())
        self.menubar.addAction(self.menuPrefer_ncias.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Principal"))
        self.dockWidget_9.setWindowTitle(_translate("MainWindow", "Visualização"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuCriar_Dataset.setTitle(_translate("MainWindow", "Criar Dataset"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuFerramentas.setTitle(_translate("MainWindow", "Ferramentas"))
        self.menuProje_o.setTitle(_translate("MainWindow", "Projeção"))
        self.menuPr_Processamento.setTitle(_translate("MainWindow", "Pré Processamento Manual"))
        self.menuFiltros.setTitle(_translate("MainWindow", "Filtros"))
        self.menuPrefer_ncias.setTitle(_translate("MainWindow", "Preferências"))
        self.menuExibir.setTitle(_translate("MainWindow", "Exibir"))
        self.dockWidget_6.setWindowTitle(_translate("MainWindow", "Caracteristicas"))
        self.dockWidget_7.setWindowTitle(_translate("MainWindow", "Individuos"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cor Classe"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Classe"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Área"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Perimetro"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Média"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Mediana"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Angulo"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Centroide X"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Centroide Y"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Centro de massa Y"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Centro de massa X"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Roi Largura"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Roi Altura"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Máximo"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Mínimo"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Mode"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "Y"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "Width"))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "Height"))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "Maior"))
        item = self.tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "Menor"))
        item = self.tableWidget.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "Circularidade"))
        item = self.tableWidget.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "Feret"))
        item = self.tableWidget.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "Densidade integrada"))
        item = self.tableWidget.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "Inclinação"))
        item = self.tableWidget.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "%Area"))
        item = self.tableWidget.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "RawIntDen"))
        item = self.tableWidget.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "FeretX"))
        item = self.tableWidget.horizontalHeaderItem(30)
        item.setText(_translate("MainWindow", "FeretY"))
        item = self.tableWidget.horizontalHeaderItem(31)
        item.setText(_translate("MainWindow", "FeretAngle"))
        item = self.tableWidget.horizontalHeaderItem(32)
        item.setText(_translate("MainWindow", "MinFeret"))
        item = self.tableWidget.horizontalHeaderItem(33)
        item.setText(_translate("MainWindow", "Proporção da Tela"))
        item = self.tableWidget.horizontalHeaderItem(34)
        item.setText(_translate("MainWindow", "Round"))
        item = self.tableWidget.horizontalHeaderItem(35)
        item.setText(_translate("MainWindow", "Solidez"))
        item = self.tableWidget.horizontalHeaderItem(36)
        item.setText(_translate("MainWindow", "MaxThr"))
        item = self.tableWidget.horizontalHeaderItem(37)
        item.setText(_translate("MainWindow", "MinThr"))
        self.dockWidget_8.setWindowTitle(_translate("MainWindow", "Projeção"))
        self.actionAbrir_Dataset.setText(_translate("MainWindow", "Abrir Dataset"))
        self.actionAbrir_Dataset.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionAtalhos.setText(_translate("MainWindow", "Atalhos"))
        self.actionSobre.setText(_translate("MainWindow", "Sobre"))
        self.actionDeteccao_de_Caracteristicas.setText(_translate("MainWindow", "Análise Morfológica"))
        self.actionDeteccao_de_Caracteristicas.setToolTip(_translate("MainWindow", "Análise Morfológica"))
        self.actionPCA.setText(_translate("MainWindow", "PCA"))
        self.actionTSNE.setText(_translate("MainWindow", "TSNE"))
        self.actionSAMMON.setText(_translate("MainWindow", "SAMMON"))
        self.actionMDS.setText(_translate("MainWindow", "MDS"))
        self.actionNormalizar_Valores.setText(_translate("MainWindow", "Normalizar Valores"))
        self.actionRecorteLivre.setText(_translate("MainWindow", "Recortar Região de Interesse"))
        self.actionDividir_Imagem.setText(_translate("MainWindow", "Dividir Imagem"))
        self.actionEqualizacao.setText(_translate("MainWindow", "Equalização"))
        self.actionMediana.setText(_translate("MainWindow", "Mediana"))
        self.actionBinarizacao.setText(_translate("MainWindow", "Binarização"))
        self.actionInversao.setText(_translate("MainWindow", "Inversão"))
        self.actionCriar_Classe.setText(_translate("MainWindow", "Criar Classe"))
        self.actionOperadores.setText(_translate("MainWindow", "Operadores"))
        self.actionteste.setText(_translate("MainWindow", "teste"))
        self.actionPre_Processamento_Automatico.setText(_translate("MainWindow", "Pré Processamento Automático"))
        self.actionPre_Processamento_Automatico.setToolTip(_translate("MainWindow", "<html><head/><body><p>Etapas de pré processamento automatico: 1° equalização - 2° mediana - 3° binarização - 4° operadores morfológicos. Certifique-se que suas imagens estajem apenas com a região de interesse.</p></body></html>"))
        self.actionImagens.setText(_translate("MainWindow", "Imagens"))
